# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-03-11 03:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellbuy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='company_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
