# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-03-14 03:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellbuy', '0002_share_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shareprice',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
